version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    restart: unless-stopped
    cpus: "1.0"
    mem_limit: 1g
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /docker/clickhouse_data:/var/lib/clickhouse

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    cpus: "2.0"
    mem_limit: 2g
    ports:
      - "3000:3000"
    volumes:
      - /docker/grafana/:/var/lib/docker/volumes/
